"""create initial tables

Revision ID: 870b875fd317
Revises: 
Create Date: 2026-03-13 23:00:31.270353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870b875fd317'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('elo_rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('language', sa.Enum('python', 'javascript', name='language'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('elo_rating', sa.Integer(), nullable=False),
    sa.Column('win_count', sa.Integer(), nullable=False),
    sa.Column('loss_count', sa.Integer(), nullable=False),
    sa.Column('draw_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bot_a_id', sa.String(), nullable=False),
    sa.Column('bot_b_id', sa.String(), nullable=False),
    sa.Column('game_type', sa.Enum('tictactoe', name='gametype'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'error', name='matchstatus'), nullable=False),
    sa.Column('winner_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot_a_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['bot_b_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_turns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(length=1), nullable=False),
    sa.Column('move', sa.JSON(), nullable=False),
    sa.Column('state_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_turns')
    op.drop_table('matches')
    op.drop_table('bots')
    op.drop_table('users')
    # ### end Alembic commands ###
